# Generated by Django 5.2.6 on 2025-10-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заявки, PVA, TRM')),
                ('created', models.DateTimeField(verbose_name='Время получения')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование комплекта')),
                ('priority', models.BooleanField(default=False, verbose_name='Приоритет')),
                ('iteration', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0', verbose_name='Итерация')),
                ('status', models.CharField(choices=[('Не взята в работу', 'Не взята в работу'), ('Отработана', 'Отработана'), ('Возвращена на доработку', 'Возвращена на доработку'), ('ON HOLD', 'ON HOLD'), ('Cancelled', 'Cancelled'), ('Отозвана', 'Отозвана')], default='Не взята в работу', max_length=50)),
                ('result', models.CharField(blank=True, max_length=100, verbose_name='Созданный процесс, TRM')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник ТДО')),
            ],
        ),
    ]
