# Generated by Django 5.2.6 on 2025-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateField(blank=True, default='2025-10-31', verbose_name='Завершено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_taken', 'Не взята в работу'), ('in_progress', 'В работе'), ('completed', 'Отработана'), ('returned', 'Возвращена на доработку'), ('on_hold', 'ON HOLD'), ('cancelled', 'Cancelled'), ('recalled', 'Отозвана')], default='Не взята в работу', max_length=50, verbose_name='Статус'),
        ),
    ]
