# Generated by Django 5.2.6 on 2025-10-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_finished_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.DateField(blank=True, null=True, verbose_name='Завершено'),
        ),
    ]
