# Generated by Django 5.2.6 on 2025-11-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('portal', 'Портал'), ('sending', 'Отправка'), ('BBB', 'ВВВ 1С КФО'), ('TRMfromSPO', 'TRM от СПО'), ('SPOKVIP', 'СПО КВИП'), ('KMforRFQRFP', 'KM для RFQ/RFP'), ('approvement', 'Утверждающий проверки')], default='Портал', max_length=50, verbose_name='Тип'),
        ),
    ]
