# Generated by Django 5.2.6 on 2025-11-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
