# Generated by Django 5.2.6 on 2025-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypes',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='en_short',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='ru_short',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
