# Generated by Django 5.2.6 on 2025-11-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_documenttypes_en_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsubtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'ordering': ('ru_name',)},
        ),
    ]
