# Generated by Django 5.2.6 on 2025-11-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_documentsubtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentarticle',
            options={'verbose_name': 'Заметка о документации', 'verbose_name_plural': 'Заметки о документации'},
        ),
        migrations.AlterModelOptions(
            name='documentsubtype',
            options={'ordering': ('name',), 'verbose_name': 'Подтип документа / заметки', 'verbose_name_plural': 'Подтипы документов / заметки'},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'ordering': ('ru_name',), 'verbose_name': 'Тип документа / заметки', 'verbose_name_plural': 'Типы документов / заметки'},
        ),
    ]
