# Generated by Django 5.2.6 on 2025-11-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_alter_documentarticle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttypes',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='documenttypes',
            name='en_short',
        ),
        migrations.RemoveField(
            model_name='documenttypes',
            name='ru_short',
        ),
    ]
