# Generated by Django 5.2.6 on 2025-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_remove_documenttypes_en_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarticle',
            name='clean_text',
            field=models.TextField(blank=True),
        ),
    ]
