# Generated by Django 5.2.6 on 2025-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, default='Ответа пока что нет...', max_length=1000)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
