# Generated by Django 5.2.7 on 2025-10-29 13:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, default='Ответа пока что нет...', max_length=1000)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('ru_short', models.CharField(max_length=5)),
                ('en_short', models.CharField(max_length=5)),
                ('sub_types', models.ManyToManyField(blank=True, related_name='doc_types', to='dccpdh2.documentsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dccpdh2.documentsubtype')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dccpdh2.documenttypes')),
            ],
        ),
    ]
