# Generated by Django 5.2.6 on 2025-11-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttypes',
            name='sub_types',
        ),
        migrations.DeleteModel(
            name='DocumentArticle',
        ),
        migrations.DeleteModel(
            name='DocumentSubType',
        ),
        migrations.DeleteModel(
            name='DocumentTypes',
        ),
    ]
