# Generated by Django 5.2.6 on 2025-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('active', models.BooleanField(choices=[(1, 'Актуален'), (0, 'Отменен')], default=1)),
                ('link_approvement', models.URLField(blank=True)),
            ],
        ),
    ]
