# Generated by Django 5.2.6 on 2025-11-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0002_remove_documenttypes_sub_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answered',
        ),
    ]
