# Generated by Django 5.2.6 on 2025-09-27 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0002_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
