# Generated by Django 5.2.6 on 2025-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0003_change_created_change_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-number']},
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('edms_link', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='procedure', to='dccpdh2.tag')),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='change', to='dccpdh2.tag'),
        ),
    ]
