# Generated by Django 5.2.6 on 2025-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0004_tag_alter_change_options_procedure_change_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('ru_short', models.CharField(max_length=5)),
                ('en_short', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('p_type', models.TextField(choices=[('PVA-процесс', 'Pva'), ('Review Transmittal', 'Review')], default='PVA-процесс')),
                ('doc_types', models.ManyToManyField(blank=True, related_name='processes', to='dccpdh2.documenttypes')),
            ],
        ),
    ]
