# Generated by Django 5.2.6 on 2025-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0005_documenttypes_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='sub_types',
            field=models.ManyToManyField(blank=True, related_name='doc_types', to='dccpdh2.documentsubtype'),
        ),
    ]
