# Generated by Django 5.2.6 on 2025-09-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0006_documentsubtype_documenttypes_sub_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dccpdh2.documentsubtype')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dccpdh2.documenttypes')),
            ],
        ),
    ]
