# Generated by Django 5.2.6 on 2025-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0007_documentarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-number'], 'verbose_name': 'Изменение', 'verbose_name_plural': 'Изменения'},
        ),
        migrations.AlterField(
            model_name='change',
            name='active',
            field=models.BooleanField(choices=[(True, 'Актуален'), (False, 'Отменен')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='change',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='change',
            name='link_approvement',
            field=models.URLField(blank=True, verbose_name='Ссылка на согласование'),
        ),
        migrations.AlterField(
            model_name='change',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='change', to='dccpdh2.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='change',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='change',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='change',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
    ]
