# Generated by Django 5.2.6 on 2025-10-09 14:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0008_alter_change_options_alter_change_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarticle',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
