# Generated by Django 5.2.6 on 2025-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0009_alter_documentarticle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(choices=[(None, 'Choose a tag'), ('ASAP', 'As soons as possbile'), ('BRB', 'Be right back'), ('TTL', 'Talk to you later')], unique=True),
        ),
    ]
