# Generated by Django 5.2.6 on 2025-10-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0010_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(choices=[('As soons as possbile', 'Asap'), ('Be right back', 'Brb'), ('Talk to you later', 'Ttl')], unique=True),
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
