# Generated by Django 5.2.6 on 2025-10-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0011_alter_tag_slug_delete_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='doc_types',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
