# Generated by Django 5.2.6 on 2025-10-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dccpdh2', '0013_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
