# Generated by Django 5.2.6 on 2025-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('active', models.BooleanField(choices=[(True, 'Актуален'), (False, 'Отменен')], default=1, verbose_name='Статус')),
                ('link_approvement', models.URLField(blank=True, verbose_name='Ссылка на согласование')),
            ],
            options={
                'verbose_name': 'Изменение',
                'verbose_name_plural': 'Изменения',
                'ordering': ['-number'],
            },
        ),
        migrations.RunSQL(
            "INSERT INTO list_of_changes_change SELECT * FROM dccpdh2_change;",
            reverse_sql="INSERT INTO dccpdh2_change SELECT * FROM list_of_changes_change;"
        )
    ]
