# Generated by Django 5.2.6 on 2025-10-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='link_approvement',
            field=models.CharField(blank=True, verbose_name='Ссылка на согласование'),
        ),
    ]
