# Generated by Django 5.2.6 on 2025-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_changes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Содержание'),
        ),
    ]
