# Generated by Django 5.2.6 on 2025-11-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_changes', '0002_alter_change_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='active',
            field=models.BooleanField(choices=[(1, 'Актуален'), (0, 'Отменен')], default=(1, 'Актуален'), verbose_name='Статус'),
        ),
    ]
