# Generated by Django 5.2.6 on 2025-11-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_changes', '0003_alter_change_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='active',
            field=models.BooleanField(choices=[(True, 'Актуален'), (False, 'Отменен')], default=True, verbose_name='Статус'),
        ),
    ]
